#!/bin/bash
# 压缩 source/images/<note_name> 目录下的图片
# brew install cwebp
# Usage: ./compress_images.sh <note_name>
Usage() {
    echo "Usage: $0 <note_name>"
    echo "This script compresses images in the source/images/<note_name> directory."
    exit 1
}

if [[ $# -ne 1 ]]; then
    Usage
fi

NOTE_NAME="$1"
TARGET_DIR="/Users/zip95297/Repository/BLOG/zjb-blog/source/images/$NOTE_NAME"

# 检查目录是否存在
if [[ ! -d "$TARGET_DIR" ]]; then
    echo "Error: Directory $TARGET_DIR does not exist."
    exit 1
fi

spinner="//--\\||"
i=0
# 压缩图片
find "$TARGET_DIR" -type f \( -iname "*.png" -o -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.gif" \) | while read img_file; do
    i=$(( (i + 1) % 8 ))
    printf "\r Extractong image: ${spinner:i:1}  "
    cwebp -q 38 "$img_file" -o "${img_file%.*}.webp" -quiet
    rm "$img_file"
done

echo "Images in $TARGET_DIR have been compressed to WebP format."
